# Permalinks
permalink:           pretty

# Setup
title:               '<asyetuntitled>'
url:                 chris-lawrie.github.io
tagline:             -- something --
paginate:            1000
paginate_path:       "/page:num/"
baseurl:             ""

# Includes
include:
  - _redirects

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# # About/contact
# author:
#   name:              Chris Lawrie
#   url:               https://twitter.com/
#   email:             ...@gmail.com

# # Custom vars
# version:             1.0.0
# github:
#   repo:              https://github.com/chris-lawrie

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-gist
